#-----------------------------
# Parameters for the search
#-----------------------------

allowed_errors: 3       # number of errors
strata_width: 3         # number of errors; corresponds to x in (best+x) mapping
kmer_length: 19
bf_size: 32      # in GB; min 1GB
nr_hashes: 3
