# Data simulation parameters are set in ../simulation_config.yaml
configfile: "../simulation_config.yaml"

# Parameters for data simulation 
bin_nr = config["number_of_bins"]
nr_rf = config["read_file_count"]
epr = config["errors_per_read"]
rl = config["read_length"]

# Creating list of wildcards
bin_list = [str(i) for i in list(range(0,bin_nr))]
read_list = [str(j) for j in list(range(0, nr_rf))]

rule make_all:
	input:
		"mapped_reads/all_sorted.sam"
	shell:
		"echo 'Done'"

include: "rules/dream_yara.smk"
include: "rules/samtools.smk"
