import subprocess
import os.path

# All parameters are set in config.yaml
configfile: "../simulation_config.yaml"

# Simulating reference
length = config["ref_size"]
bin_nr = config["number_of_bins"]
ht = config["haplotype_count"]

# Simulating reads
epr = config["errors_per_read"]
rl = config["read_length"]
rpg = config["reads_per_genome"]

# An equal number of reads is sampled from each genome
rc = rpg * ht * bin_nr

# Helper variables
bins = [*range(0, bin_nr, 1)]

#workdir: "/home/evelia95/A2-metagenome-snakemake/raptor-data-simulation"

rule make_all:
	input:
		reads = expand("../../../../../group/ag_abi/eaasna/reads/{bin}.fastq", bin=bins)
	params:
		t = 1
	shell:
		"echo 'Done'"

rule create_ref:		
	output:
		"../../../../../group/ag_abi/eaasna/bins/ref.fasta"
	params:
		t = 1
	shell:
		"./scripts/create_ref.sh {length}"

rule divide_into_bins:		
	input:
		"../../../../../group/ag_abi/eaasna/bins/ref.fasta"
	output:
		expand("../../../../../group/ag_abi/eaasna/bins/{bin}.fasta", bin=bins)
	params:
		t = 1
	shell:
		"./scripts/divide_into_bins.sh {length} {bin_nr} {ht}"

rule sample_reads:
	input:
		"../../../../../group/ag_abi/eaasna/bins/{bin}.fasta"
	output:
		"../../../../../group/ag_abi/eaasna/reads/{bin}.fastq"
	params:
		t = 2
	shell:
		"./scripts/sample_reads.sh {bin_nr} {epr} {rl} {rc} {ht}"
