# Data simulation parameters are set in ../simulation_config.yaml
configfile: "../simulation_config.yaml"

# Parameters for data simulation 
bin_nr = config["number_of_bins"]
epr = config["errors_per_read"]
rl = config["read_length"]

# Creating list of wildcards
bin_list = [str(i) for i in list(range(0,bin_nr))]

rule make_all:
	input:
		"{params.dir}/mapped_reads/all_sorted.sam"
	params:
		t = 1,
		dir = "../../NO_BACKUP/simulated_metagenome/MG1"
	resources:
		nodelist = "cmp[241]"
	shell:
		"echo 'Done'"

include: "rules/dream_yara.smk"
include: "rules/samtools.smk"
