# Data simulation parameters are set in ../simulation_config.yaml
configfile: "../simulation_config.yaml"

# Parameters for data simulation 
bin_nr = config["number_of_bins"]
epr = config["errors_per_read"]
rl = config["read_length"]

# Creating list of wildcards
bin_list = [str(i) for i in list(range(0,bin_nr))]

workdir: "/nfs/buffer/ag_abi/eaasna/allegro/MG1"

rule make_all:
	input:
		"mapped_reads/all_sorted.sam"
	resources:
		nodelist = "cmp[227]"
	benchmark:
		repeat("benchmarks/all.txt", 2)
	shell:
		"echo 'Done'"

include: "rules/dream_yara.smk"
include: "rules/samtools.smk"
